#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : PyCRAM # The title of the doc. Will be placed in the left navbar.
author                      : Jonas Dech  # The author of the doc
copyright                   : "2025"  # Copyright year to be placed in the footer
logo                        : "../images/pycram_logo.png"  # A path to the doc logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: doc.tex
    use_jupyterbook_latex: false

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the doc exists on the web
repository:
  url: https://github.com/cram2/pycram  # Online location of your doc
  path_to_book: docs  # Optional path to your doc, relative to the repository root
  branch: dev  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your doc
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  show_navbar_depth: 0


sphinx:
  extra_extensions:
    - sphinx_proof
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.autosummary'
    - 'autoapi.extension'
  config:
    suppress_warnings: ["mystnb.unknown_mime_type"]
    autosummary_generate: False
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme_options:
      logo:
        image_light: ../images/new_pycram_logo_clean.svg
        image_dark: ../images/new_pycram_logo_clean_dark.svg
    autoapi_dirs: ['../../src']
    autoapi_add_toctree_entry: True
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist